<?php
/**
  * Implementation of hook_menu().
  */
function facebook_register_menu() {
   $items['facebook/register'] = array(
      'title' => 'Facebook Register',
      'description' => 'Register new account using facebook profile',
      'page callback' => 'authen',
      'access arguments' => array('access content'),
      'type' => MENU_NORMAL_ITEM,
      'file' => 'facebook_register.admin.inc',
   );
   return $items;
}

